; PlatformIO Project Configuration File
;
; Arduino-ESP32 3.3.9 / ESP-IDF 5.5.4
; Change default_envs to select an example under examples/.

[platformio]
default_envs = Lvgl_CIT_SGM41562
src_dir = examples/${platformio.default_envs}
lib_dir = libraries

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 4MB
board_build.flash_mode = qio
board_build.f_cpu = 160000000L
board_build.partitions = huge_app.csv

build_flags =
    -D CORE_DEBUG_LEVEL=0
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

[env:Battery_Voltage]
[env:Breathing_Light]
[env:ChipScan]
[env:CST816T]
[env:Deep_Sleep]
[env:ETA4662]
[env:GFX]
[env:IMU]
[env:IMU_Level]
[env:Light_Sleep]
[env:Light_Sleep_Wakeup]
[env:Lvgl_CIT_ETA4662]
[env:Lvgl_CIT_SGM41562]
[env:SGM41562]
